os:
  - linux
  - osx

language: generic
node_js: "4"
python: "2.7"

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - lldb-3.9
    - python-lldb-3.9

before_script:
  - npm install
  - curl https://sh.rustup.rs -sSf | sh -s - -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - |
    if [ $TRAVIS_OS_NAME = linux ]
    then
       export LLDB_EXECUTABLE=lldb-3.9
       echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
    fi
  - |
    if [ $TRAVIS_OS_NAME = osx ]
    then
      export PATH=/usr/bin:$PATH
    fi
  - which python
  - python --version
  - export LLDB_LOGFILE=$HOME/lldb.log

script:
  - npm test

after_failure:
  - env
  - cat $HOME/lldb.log
  - ls -R

branches:
  only:
  - master
